/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/change-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change login (email) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "email": "changed_f676dd96@example.com",
                     *       "password": "password123"
                     *     }
                     */
                    "application/json": {
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description changes the login email */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "An email has been sent to you with a link to verify your login change"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "password": "password123",
                     *       "new-password": "newpassword123",
                     *       "password-confirm": "newpassword123"
                     *     }
                     */
                    "application/json": {
                        password: string;
                        "new-password": string;
                        "password-confirm": string;
                    };
                };
            };
            responses: {
                /** @description changes the password */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "Your password has been changed"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/close-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close account (unauthorized) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "password": "password123"
                     *     }
                     */
                    "application/json": {
                        password: string;
                    };
                };
            };
            responses: {
                /** @description closes the account */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "Your account has been closed"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/create-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "email": "new_44fb2e23@example.com",
                     *       "password": "password123",
                     *       "password-confirm": "password123"
                     *     }
                     */
                    "application/json": {
                        email: string;
                        password: string;
                        "password-confirm": string;
                    };
                };
            };
            responses: {
                /** @description creates a new account */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "An email has been sent to you with a link to verify your account"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns error for short password */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "field-error": [
                         *         "password",
                         *         "passwords do not match"
                         *       ],
                         *       "error": "There was an error creating your account"
                         *     }
                         */
                        "application/json": {
                            "field-error": string[];
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** index */
        get: {
            parameters: {
                query?: {
                    /** @example Good */
                    condition?: string;
                    /** @example desc */
                    dir?: string;
                    /** @example 5 */
                    limit?: number;
                    /** @example 1 */
                    page?: number;
                    /** @example NES */
                    platform?: string;
                    /** @example aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa */
                    q?: string;
                    /** @example USA */
                    region?: string;
                    /** @example year */
                    sort?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description truncates excessively long search queries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [],
                         *       "pagination": {
                         *         "scaffold_url": "/api/v1/games?q=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&page=__pagy_page__&limit=20",
                         *         "first_url": "/api/v1/games?q=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&page=1&limit=20",
                         *         "prev_url": "/api/v1/games?q=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&page=&limit=20",
                         *         "page_url": "/api/v1/games?q=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&page=1&limit=20",
                         *         "next_url": "/api/v1/games?q=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&page=&limit=20",
                         *         "last_url": "/api/v1/games?q=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&page=1&limit=20",
                         *         "count": 0,
                         *         "page": 1,
                         *         "limit": 20,
                         *         "vars": {
                         *           "count_args": [
                         *             "all"
                         *           ],
                         *           "ends": true,
                         *           "limit": 20,
                         *           "outset": 0,
                         *           "page": 1,
                         *           "page_param": "page",
                         *           "size": 7,
                         *           "metadata": [
                         *             "scaffold_url",
                         *             "first_url",
                         *             "prev_url",
                         *             "page_url",
                         *             "next_url",
                         *             "last_url",
                         *             "count",
                         *             "page",
                         *             "limit",
                         *             "vars",
                         *             "pages",
                         *             "last",
                         *             "in",
                         *             "from",
                         *             "to",
                         *             "prev",
                         *             "next",
                         *             "series"
                         *           ],
                         *           "steps": false,
                         *           "limit_param": "limit",
                         *           "limit_max": 100,
                         *           "limit_extra": true,
                         *           "count": 0
                         *         },
                         *         "pages": 1,
                         *         "last": 1,
                         *         "in": 0,
                         *         "from": 0,
                         *         "to": 0,
                         *         "prev": null,
                         *         "next": null,
                         *         "series": [
                         *           "1"
                         *         ]
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: {
                                id: number;
                                condition: string;
                                created_at: string;
                                developer: string;
                                genre: string;
                                notes: string;
                                platform: string;
                                publisher: string;
                                region: string;
                                title: string;
                                updated_at: string;
                                user_id: number;
                                year: number;
                            }[];
                            pagination: {
                                scaffold_url: string;
                                first_url: string;
                                prev_url: string;
                                page_url: string;
                                next_url: string;
                                last_url: string;
                                count: number;
                                page: number;
                                limit: number;
                                vars: {
                                    count_args: string[];
                                    ends: boolean;
                                    limit: number;
                                    outset: number;
                                    page: number;
                                    page_param: string;
                                    size: number;
                                    metadata: string[];
                                    steps: boolean;
                                    limit_param: string;
                                    limit_max: number;
                                    limit_extra: boolean;
                                    count: number;
                                };
                                pages: number;
                                last: number;
                                in: number;
                                from: number;
                                to: number;
                                prev: unknown;
                                next: unknown;
                                series: string[];
                            };
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a game */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "game": {
                     *         "title": "The Legend of Zelda",
                     *         "platform": "NES",
                     *         "year": 1986,
                     *         "genre": "Action-adventure",
                     *         "developer": "Nintendo",
                     *         "publisher": "Nintendo",
                     *         "region": "USA",
                     *         "condition": "Good",
                     *         "notes": "Boxed copy"
                     *       }
                     *     }
                     */
                    "application/json": {
                        game: {
                            title: string;
                            platform: string;
                            year: number;
                            genre: string;
                            developer: string;
                            publisher: string;
                            region: string;
                            condition: string;
                            notes: string;
                        };
                    };
                };
            };
            responses: {
                /** @description creates a game for the authenticated user */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "id": 227,
                         *         "condition": "Good",
                         *         "created_at": "2026-06-06T13:51:58.399Z",
                         *         "developer": "Nintendo",
                         *         "genre": "Action-adventure",
                         *         "notes": "Boxed copy",
                         *         "platform": "NES",
                         *         "publisher": "Nintendo",
                         *         "region": "USA",
                         *         "title": "The Legend of Zelda",
                         *         "updated_at": "2026-06-06T13:51:58.399Z",
                         *         "user_id": 460,
                         *         "year": 1986
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: {
                                id: number;
                                condition: string;
                                created_at: string;
                                developer: string;
                                genre: string;
                                notes: string;
                                platform: string;
                                publisher: string;
                                region: string;
                                title: string;
                                updated_at: string;
                                user_id: number;
                                year: number;
                            };
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description returns 422 for invalid params */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "errors": {
                         *         "title": [
                         *           "can't be blank"
                         *         ],
                         *         "genre": [
                         *           "can't be blank"
                         *         ],
                         *         "developer": [
                         *           "can't be blank"
                         *         ]
                         *       }
                         *     }
                         */
                        "application/json": {
                            errors: {
                                title: string[];
                                genre: string[];
                                developer: string[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        /** OPTIONS /api/v1/games */
        options: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /** @example {} */
                    "application/x-www-form-urlencoded": Record<string, never>;
                };
            };
            responses: {
                /** @description returns CORS headers on preflight request */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a game */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 1 */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description returns a game belonging to the authenticated user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "id": 225,
                         *         "condition": "Good",
                         *         "created_at": "2026-06-06T13:51:58.380Z",
                         *         "developer": "Nintendo",
                         *         "genre": "Action-adventure",
                         *         "notes": "Boxed copy",
                         *         "platform": "NES",
                         *         "publisher": "Nintendo",
                         *         "region": "USA",
                         *         "title": "The Legend of Zelda",
                         *         "updated_at": "2026-06-06T13:51:58.380Z",
                         *         "user_id": 456,
                         *         "year": 1986
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: {
                                id: number;
                                condition: string;
                                created_at: string;
                                developer: string;
                                genre: string;
                                notes: string;
                                platform: string;
                                publisher: string;
                                region: string;
                                title: string;
                                updated_at: string;
                                user_id: number;
                                year: number;
                            };
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description returns 404 for unknown game */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Not found"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a game */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 1 */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description deletes a game belonging to the authenticated user */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description returns 404 for unknown game */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Not found"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a game */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 1 */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "game": {
                     *         "title": "Zelda II",
                     *         "platform": "NES",
                     *         "year": 1986,
                     *         "genre": "Action-adventure",
                     *         "developer": "Nintendo",
                     *         "publisher": "Nintendo",
                     *         "region": "USA",
                     *         "condition": "Good",
                     *         "notes": "Boxed copy"
                     *       }
                     *     }
                     */
                    "application/json": {
                        game: {
                            title: string;
                            platform: string;
                            year: number;
                            genre: string;
                            developer: string;
                            publisher: string;
                            region: string;
                            condition: string;
                            notes: string;
                        };
                    };
                };
            };
            responses: {
                /** @description updates a game belonging to the authenticated user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "user_id": 462,
                         *         "title": "Zelda II",
                         *         "platform": "NES",
                         *         "year": 1986,
                         *         "genre": "Action-adventure",
                         *         "developer": "Nintendo",
                         *         "publisher": "Nintendo",
                         *         "region": "USA",
                         *         "condition": "Good",
                         *         "notes": "Boxed copy",
                         *         "id": 228,
                         *         "created_at": "2026-06-06T13:51:58.409Z",
                         *         "updated_at": "2026-06-06T13:51:58.411Z"
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: {
                                user_id: number;
                                title: string;
                                platform: string;
                                year: number;
                                genre: string;
                                developer: string;
                                publisher: string;
                                region: string;
                                condition: string;
                                notes: string;
                                id: number;
                                created_at: string;
                                updated_at: string;
                            };
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description returns 404 for unknown game */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Not found"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description returns 422 for invalid params */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "errors": {
                         *         "title": [
                         *           "can't be blank"
                         *         ]
                         *       }
                         *     }
                         */
                        "application/json": {
                            errors: {
                                title: string[];
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "email": "user_7290e2e1@example.com",
                     *       "password": "password123"
                     *     }
                     */
                    "application/json": {
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description returns a JWT token in Authorization header */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "You have been logged in"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns 401 for invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "field-error": [
                         *         "email",
                         *         "no matching login"
                         *       ],
                         *       "error": "There was an error logging in"
                         *     }
                         */
                        "application/json": {
                            "field-error": string[];
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /** @example {} */
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description logs out the current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "You have been logged out"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "key": "440_Jn97ZPEaVRe5M-6dvHqsBorUnNtb6ZpQtQF46W5Wukw",
                     *       "password": "newpassword456",
                     *       "password-confirm": "newpassword456"
                     *     }
                     */
                    "application/json": {
                        key: string;
                        password: string;
                        "password-confirm": string;
                    };
                };
            };
            responses: {
                /** @description resets password with valid key */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "Your password has been reset"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns error for invalid reset key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "There was an error resetting your password"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reset-password-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "email": "user_144107b0@example.com"
                     *     }
                     */
                    "application/json": {
                        email: string;
                    };
                };
            };
            responses: {
                /** @description requests a password reset email */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "An email has been sent to you with a link to reset the password for your account"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns error for unknown email */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "field-error": [
                         *         "email",
                         *         "no matching login"
                         *       ],
                         *       "error": "There was an error requesting a password reset"
                         *     }
                         */
                        "application/json": {
                            "field-error": string[];
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verify-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "key": "441_rgy-CS1NDovwX88UO8OrM_OXMC_1NeP39wqlECrpOTo"
                     *     }
                     */
                    "application/json": {
                        key: string;
                    };
                };
            };
            responses: {
                /** @description verifies account with valid key */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "Your account has been verified"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns error for invalid verification key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Unable to verify account"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verify-account-resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend account verification email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "email": "unverified_483b24ee@example.com"
                     *     }
                     */
                    "application/json": {
                        email: string;
                    };
                };
            };
            responses: {
                /** @description resends verification email */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "An email has been sent to you with a link to verify your account"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Unable to resend verify account email"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verify-login-change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify login change */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "key": "445_aZQmAtdtJM1-S3MaHfeHbKwwgM5se9LkY0GZ8pqcZUI"
                     *     }
                     */
                    "application/json": {
                        key: string;
                    };
                };
            };
            responses: {
                /** @description verifies login change with valid key */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "Your login change has been verified"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns error for invalid key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Unable to verify login change"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
