/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/change-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change login (email) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "email": "changed_0d7340d9@example.com",
                     *       "password": "password123"
                     *     }
                     */
                    "application/json": {
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description changes the login email */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "An email has been sent to you with a link to verify your login change"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "password": "password123",
                     *       "new-password": "newpassword123",
                     *       "password-confirm": "newpassword123"
                     *     }
                     */
                    "application/json": {
                        password: string;
                        "new-password": string;
                        "password-confirm": string;
                    };
                };
            };
            responses: {
                /** @description changes the password */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "Your password has been changed"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/close-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close account (unauthorized) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "password": "password123"
                     *     }
                     */
                    "application/json": {
                        password: string;
                    };
                };
            };
            responses: {
                /** @description closes the account */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "Your account has been closed"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/create-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "email": "new_f2609516@example.com",
                     *       "password": "password123",
                     *       "password-confirm": "password123"
                     *     }
                     */
                    "application/json": {
                        email: string;
                        password: string;
                        "password-confirm": string;
                    };
                };
            };
            responses: {
                /** @description creates a new account */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "An email has been sent to you with a link to verify your account"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns error for short password */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "field-error": [
                         *         "password",
                         *         "passwords do not match"
                         *       ],
                         *       "error": "There was an error creating your account"
                         *     }
                         */
                        "application/json": {
                            "field-error": string[];
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List games */
        get: {
            parameters: {
                query?: {
                    /** @example Good */
                    condition?: string;
                    /** @example desc */
                    dir?: string;
                    /**
                     * @description Number of items per page
                     * @example 5
                     */
                    limit?: number;
                    /**
                     * @description Page number
                     * @example 1
                     */
                    page?: number;
                    /** @example NES */
                    platform?: string;
                    /** @example zelda */
                    q?: string;
                    /** @example USA */
                    region?: string;
                    /** @example year */
                    sort?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description sorts games by year descending */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": 300,
                         *           "condition": "Good",
                         *           "created_at": "2026-06-06T12:05:02.904Z",
                         *           "developer": "Nintendo",
                         *           "genre": "Action-adventure",
                         *           "notes": "Boxed copy",
                         *           "platform": "NES",
                         *           "publisher": "Nintendo",
                         *           "region": "USA",
                         *           "title": "New Game",
                         *           "updated_at": "2026-06-06T12:05:02.904Z",
                         *           "user_id": 716,
                         *           "year": 2020
                         *         },
                         *         {
                         *           "id": 299,
                         *           "condition": "Good",
                         *           "created_at": "2026-06-06T12:05:02.903Z",
                         *           "developer": "Nintendo",
                         *           "genre": "Action-adventure",
                         *           "notes": "Boxed copy",
                         *           "platform": "NES",
                         *           "publisher": "Nintendo",
                         *           "region": "USA",
                         *           "title": "Old Game",
                         *           "updated_at": "2026-06-06T12:05:02.903Z",
                         *           "user_id": 716,
                         *           "year": 1985
                         *         }
                         *       ],
                         *       "pagination": {
                         *         "scaffold_url": "/games?sort=year&dir=desc&page=__pagy_page__&limit=20",
                         *         "first_url": "/games?sort=year&dir=desc&page=1&limit=20",
                         *         "prev_url": "/games?sort=year&dir=desc&page=&limit=20",
                         *         "page_url": "/games?sort=year&dir=desc&page=1&limit=20",
                         *         "next_url": "/games?sort=year&dir=desc&page=&limit=20",
                         *         "last_url": "/games?sort=year&dir=desc&page=1&limit=20",
                         *         "count": 2,
                         *         "page": 1,
                         *         "limit": 20,
                         *         "vars": {
                         *           "count_args": [
                         *             "all"
                         *           ],
                         *           "ends": true,
                         *           "limit": 20,
                         *           "outset": 0,
                         *           "page": 1,
                         *           "page_param": "page",
                         *           "size": 7,
                         *           "metadata": [
                         *             "scaffold_url",
                         *             "first_url",
                         *             "prev_url",
                         *             "page_url",
                         *             "next_url",
                         *             "last_url",
                         *             "count",
                         *             "page",
                         *             "limit",
                         *             "vars",
                         *             "pages",
                         *             "last",
                         *             "in",
                         *             "from",
                         *             "to",
                         *             "prev",
                         *             "next",
                         *             "series"
                         *           ],
                         *           "count": 2,
                         *           "steps": false,
                         *           "limit_param": "limit",
                         *           "limit_max": 100,
                         *           "limit_extra": true
                         *         },
                         *         "pages": 1,
                         *         "last": 1,
                         *         "in": 2,
                         *         "from": 1,
                         *         "to": 2,
                         *         "prev": null,
                         *         "next": null,
                         *         "series": [
                         *           "1"
                         *         ]
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: {
                                id: number;
                                condition: string;
                                created_at: string;
                                developer: string;
                                genre: string;
                                notes: string;
                                platform: string;
                                publisher: string;
                                region: string;
                                title: string;
                                updated_at: string;
                                user_id: number;
                                year: number;
                            }[];
                            pagination: {
                                scaffold_url: string;
                                first_url: string;
                                prev_url: string;
                                page_url: string;
                                next_url: string;
                                last_url: string;
                                count: number;
                                page: number;
                                limit: number;
                                vars: {
                                    count_args: string[];
                                    ends: boolean;
                                    limit: number;
                                    outset: number;
                                    page: number;
                                    page_param: string;
                                    size: number;
                                    metadata: string[];
                                    count: number;
                                    steps?: boolean;
                                    limit_param?: string;
                                    limit_max?: number;
                                    limit_extra?: boolean;
                                };
                                pages: number;
                                last: number;
                                in: number;
                                from: number;
                                to: number;
                                prev: unknown;
                                next: unknown;
                                series: string[];
                            };
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a game */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "game": {
                     *         "title": "The Legend of Zelda",
                     *         "platform": "NES",
                     *         "year": 1986,
                     *         "genre": "Action-adventure",
                     *         "developer": "Nintendo",
                     *         "publisher": "Nintendo",
                     *         "region": "USA",
                     *         "condition": "Good",
                     *         "notes": "Boxed copy"
                     *       }
                     *     }
                     */
                    "application/json": {
                        game: {
                            title: string;
                            platform: string;
                            year: number;
                            genre: string;
                            developer: string;
                            publisher?: string;
                            region?: string;
                            condition?: string;
                            notes?: string;
                        };
                    };
                };
            };
            responses: {
                /** @description creates a game for the authenticated user */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": 303,
                         *       "condition": "Good",
                         *       "created_at": "2026-06-06T12:05:02.928Z",
                         *       "developer": "Nintendo",
                         *       "genre": "Action-adventure",
                         *       "notes": "Boxed copy",
                         *       "platform": "NES",
                         *       "publisher": "Nintendo",
                         *       "region": "USA",
                         *       "title": "The Legend of Zelda",
                         *       "updated_at": "2026-06-06T12:05:02.928Z",
                         *       "year": 1986,
                         *       "user_id": 721
                         *     }
                         */
                        "application/json": {
                            id: number;
                            condition: string | null;
                            created_at: string;
                            developer: string;
                            genre: string;
                            notes: string | null;
                            platform: string;
                            publisher: string | null;
                            region: string | null;
                            title: string;
                            updated_at: string;
                            year: number;
                            user_id?: number;
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description returns 422 for invalid params */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "errors": {
                         *         "title": [
                         *           "can't be blank"
                         *         ],
                         *         "genre": [
                         *           "can't be blank"
                         *         ],
                         *         "developer": [
                         *           "can't be blank"
                         *         ]
                         *       }
                         *     }
                         */
                        "application/json": {
                            errors: {
                                title: string[];
                                genre?: string[];
                                developer?: string[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a game */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 1 */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description returns a game belonging to the authenticated user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": 301,
                         *       "condition": "Good",
                         *       "created_at": "2026-06-06T12:05:02.909Z",
                         *       "developer": "Nintendo",
                         *       "genre": "Action-adventure",
                         *       "notes": "Boxed copy",
                         *       "platform": "NES",
                         *       "publisher": "Nintendo",
                         *       "region": "USA",
                         *       "title": "The Legend of Zelda",
                         *       "updated_at": "2026-06-06T12:05:02.909Z",
                         *       "year": 1986,
                         *       "user_id": 717
                         *     }
                         */
                        "application/json": {
                            id: number;
                            condition: string | null;
                            created_at: string;
                            developer: string;
                            genre: string;
                            notes: string | null;
                            platform: string;
                            publisher: string | null;
                            region: string | null;
                            title: string;
                            updated_at: string;
                            year: number;
                            user_id?: number;
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description returns 404 for unknown game */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Not found"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a game */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 1 */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description deletes a game belonging to the authenticated user */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description returns 404 for unknown game */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Not found"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a game */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 1 */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "game": {
                     *         "title": "Zelda II",
                     *         "platform": "NES",
                     *         "year": 1986,
                     *         "genre": "Action-adventure",
                     *         "developer": "Nintendo",
                     *         "publisher": "Nintendo",
                     *         "region": "USA",
                     *         "condition": "Good",
                     *         "notes": "Boxed copy"
                     *       }
                     *     }
                     */
                    "application/json": {
                        game: {
                            title: string;
                            platform?: string;
                            year?: number;
                            genre?: string;
                            developer?: string;
                            publisher?: string;
                            region?: string;
                            condition?: string;
                            notes?: string;
                        };
                    };
                };
            };
            responses: {
                /** @description updates a game belonging to the authenticated user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "title": "Zelda II",
                         *       "year": 1986,
                         *       "id": 304,
                         *       "condition": "Good",
                         *       "created_at": "2026-06-06T12:05:02.938Z",
                         *       "developer": "Nintendo",
                         *       "genre": "Action-adventure",
                         *       "notes": "Boxed copy",
                         *       "platform": "NES",
                         *       "publisher": "Nintendo",
                         *       "region": "USA",
                         *       "updated_at": "2026-06-06T12:05:02.940Z",
                         *       "user_id": 723
                         *     }
                         */
                        "application/json": {
                            title: string;
                            year: number;
                            id: number;
                            condition: string | null;
                            created_at: string;
                            developer: string;
                            genre: string;
                            notes: string | null;
                            platform: string;
                            publisher: string | null;
                            region: string | null;
                            updated_at: string;
                            user_id?: number;
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description returns 404 for unknown game */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Not found"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description returns 422 for invalid params */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "errors": {
                         *         "title": [
                         *           "can't be blank"
                         *         ]
                         *       }
                         *     }
                         */
                        "application/json": {
                            errors: {
                                title: string[];
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "email": "user_5ffdc888@example.com",
                     *       "password": "password123"
                     *     }
                     */
                    "application/json": {
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description returns a JWT token in Authorization header */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "You have been logged in"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns 401 for invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "field-error": [
                         *         "email",
                         *         "no matching login"
                         *       ],
                         *       "error": "There was an error logging in"
                         *     }
                         */
                        "application/json": {
                            "field-error": string[];
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /** @example {} */
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description logs out the current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "You have been logged out"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "key": "701_QA2LJa9cDf4SsbJHvp_oSzYqD-P1oqx_Typd4PhbdFo",
                     *       "password": "newpassword456",
                     *       "password-confirm": "newpassword456"
                     *     }
                     */
                    "application/json": {
                        key: string;
                        password: string;
                        "password-confirm": string;
                    };
                };
            };
            responses: {
                /** @description resets password with valid key */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "Your password has been reset"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns error for invalid reset key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "There was an error resetting your password"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reset-password-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "email": "user_f4081b54@example.com"
                     *     }
                     */
                    "application/json": {
                        email: string;
                    };
                };
            };
            responses: {
                /** @description requests a password reset email */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "An email has been sent to you with a link to reset the password for your account"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns error for unknown email */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "field-error": [
                         *         "email",
                         *         "no matching login"
                         *       ],
                         *       "error": "There was an error requesting a password reset"
                         *     }
                         */
                        "application/json": {
                            "field-error": string[];
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verify-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "key": "702_y0nQBY4yItqARYIm6ple6lPHKSb5D_btK5mlf5b5cXs"
                     *     }
                     */
                    "application/json": {
                        key: string;
                    };
                };
            };
            responses: {
                /** @description verifies account with valid key */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "Your account has been verified"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns error for invalid verification key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Unable to verify account"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verify-account-resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend account verification email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "email": "unverified_56a9011c@example.com"
                     *     }
                     */
                    "application/json": {
                        email: string;
                    };
                };
            };
            responses: {
                /** @description resends verification email */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "An email has been sent to you with a link to verify your account"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Unable to resend verify account email"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verify-login-change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify login change */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "key": "706_wGxEx4HXqHyfm4kowwIfAHdZpcZPSZass-SW7yN81pw"
                     *     }
                     */
                    "application/json": {
                        key: string;
                    };
                };
            };
            responses: {
                /** @description verifies login change with valid key */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "Your login change has been verified"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns error for invalid key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Unable to verify login change"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
