/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/change-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change login (email) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "email": "changed_1743fb2c@example.com",
                     *       "password": "password123"
                     *     }
                     */
                    "application/json": {
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description changes the login email */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "An email has been sent to you with a link to verify your login change"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "password": "password123",
                     *       "new-password": "newpassword123",
                     *       "password-confirm": "newpassword123"
                     *     }
                     */
                    "application/json": {
                        password: string;
                        "new-password": string;
                        "password-confirm": string;
                    };
                };
            };
            responses: {
                /** @description changes the password */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "Your password has been changed"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/close-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close account (unauthorized) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "password": "password123"
                     *     }
                     */
                    "application/json": {
                        password: string;
                    };
                };
            };
            responses: {
                /** @description closes the account */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "Your account has been closed"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/create-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "email": "new_cfb35166@example.com",
                     *       "password": "password123",
                     *       "password-confirm": "password123"
                     *     }
                     */
                    "application/json": {
                        email: string;
                        password: string;
                        "password-confirm": string;
                    };
                };
            };
            responses: {
                /** @description creates a new account */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "An email has been sent to you with a link to verify your account"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns error for short password */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "field-error": [
                         *         "password",
                         *         "passwords do not match"
                         *       ],
                         *       "error": "There was an error creating your account"
                         *     }
                         */
                        "application/json": {
                            "field-error": string[];
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List games (unauthorized) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description returns a list of games */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "id": 73,
                         *         "condition": "Good",
                         *         "created_at": "2026-06-05T15:19:07.629Z",
                         *         "developer": "Nintendo",
                         *         "genre": "Action-adventure",
                         *         "notes": "Boxed copy",
                         *         "platform": "NES",
                         *         "publisher": "Nintendo",
                         *         "region": "NTSC",
                         *         "title": "The Legend of Zelda",
                         *         "updated_at": "2026-06-05T15:19:07.629Z",
                         *         "year": 1986
                         *       }
                         *     ]
                         */
                        "application/json": {
                            id: number;
                            condition: string | null;
                            created_at: string;
                            developer: string;
                            genre: string;
                            notes: string | null;
                            platform: string;
                            publisher: string | null;
                            region: string | null;
                            title: string;
                            updated_at: string;
                            year: number;
                        }[];
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a game (unauthorized) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "game": {
                     *         "title": "The Legend of Zelda",
                     *         "platform": "NES",
                     *         "year": 1986,
                     *         "genre": "Action-adventure",
                     *         "developer": "Nintendo",
                     *         "publisher": "Nintendo",
                     *         "region": "NTSC",
                     *         "condition": "Good",
                     *         "notes": "Boxed copy"
                     *       }
                     *     }
                     */
                    "application/json": {
                        game: {
                            title: string;
                            platform: string;
                            year: number;
                            genre: string;
                            developer: string;
                            publisher?: string;
                            region?: string;
                            condition?: string;
                            notes?: string;
                        };
                    };
                };
            };
            responses: {
                /** @description creates a game */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": 75,
                         *       "condition": "Good",
                         *       "created_at": "2026-06-05T15:19:07.651Z",
                         *       "developer": "Nintendo",
                         *       "genre": "Action-adventure",
                         *       "notes": "Boxed copy",
                         *       "platform": "NES",
                         *       "publisher": "Nintendo",
                         *       "region": "NTSC",
                         *       "title": "The Legend of Zelda",
                         *       "updated_at": "2026-06-05T15:19:07.651Z",
                         *       "year": 1986
                         *     }
                         */
                        "application/json": {
                            id: number;
                            condition: string | null;
                            created_at: string;
                            developer: string;
                            genre: string;
                            notes: string | null;
                            platform: string;
                            publisher: string | null;
                            region: string | null;
                            title: string;
                            updated_at: string;
                            year: number;
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description returns 422 for invalid params */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "errors": {
                         *         "title": [
                         *           "can't be blank"
                         *         ]
                         *       }
                         *     }
                         */
                        "application/json": {
                            errors: {
                                title: string[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a game (unauthorized) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 1 */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description returns a game */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": 74,
                         *       "condition": "Good",
                         *       "created_at": "2026-06-05T15:19:07.637Z",
                         *       "developer": "Nintendo",
                         *       "genre": "Action-adventure",
                         *       "notes": "Boxed copy",
                         *       "platform": "NES",
                         *       "publisher": "Nintendo",
                         *       "region": "NTSC",
                         *       "title": "The Legend of Zelda",
                         *       "updated_at": "2026-06-05T15:19:07.637Z",
                         *       "year": 1986
                         *     }
                         */
                        "application/json": {
                            id: number;
                            condition: string | null;
                            created_at: string;
                            developer: string;
                            genre: string;
                            notes: string | null;
                            platform: string;
                            publisher: string | null;
                            region: string | null;
                            title: string;
                            updated_at: string;
                            year: number;
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description returns 404 for unknown game */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Not found"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a game (unauthorized) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 1 */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description deletes a game */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description returns 404 for unknown game */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Not found"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a game (unauthorized) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 1 */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "game": {
                     *         "title": "Zelda II",
                     *         "platform": "NES",
                     *         "year": 1986,
                     *         "genre": "Action-adventure",
                     *         "developer": "Nintendo",
                     *         "publisher": "Nintendo",
                     *         "region": "NTSC",
                     *         "condition": "Good",
                     *         "notes": "Boxed copy"
                     *       }
                     *     }
                     */
                    "application/json": {
                        game: {
                            title: string;
                            platform?: string;
                            year?: number;
                            genre?: string;
                            developer?: string;
                            publisher?: string;
                            region?: string;
                            condition?: string;
                            notes?: string;
                        };
                    };
                };
            };
            responses: {
                /** @description updates a game */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "title": "Zelda II",
                         *       "year": 1986,
                         *       "id": 76,
                         *       "condition": "Good",
                         *       "created_at": "2026-06-05T15:19:07.657Z",
                         *       "developer": "Nintendo",
                         *       "genre": "Action-adventure",
                         *       "notes": "Boxed copy",
                         *       "platform": "NES",
                         *       "publisher": "Nintendo",
                         *       "region": "NTSC",
                         *       "updated_at": "2026-06-05T15:19:07.661Z"
                         *     }
                         */
                        "application/json": {
                            title: string;
                            year: number;
                            id: number;
                            condition: string | null;
                            created_at: string;
                            developer: string;
                            genre: string;
                            notes: string | null;
                            platform: string;
                            publisher: string | null;
                            region: string | null;
                            updated_at: string;
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Please login to continue"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description returns 404 for unknown game */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Not found"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description returns 422 for invalid params */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "errors": {
                         *         "title": [
                         *           "can't be blank"
                         *         ]
                         *       }
                         *     }
                         */
                        "application/json": {
                            errors: {
                                title: string[];
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "email": "user_f1fa8a62@example.com",
                     *       "password": "password123"
                     *     }
                     */
                    "application/json": {
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description returns a JWT token in Authorization header */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "You have been logged in"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns 401 for invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "field-error": [
                         *         "email",
                         *         "no matching login"
                         *       ],
                         *       "error": "There was an error logging in"
                         *     }
                         */
                        "application/json": {
                            "field-error": string[];
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /** @example {} */
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description logs out the current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "You have been logged out"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "key": "268_58xC0Omdu4XrUmj_LmQF8BLCv8rhR7JAuWEe5wfoofo",
                     *       "password": "newpassword456",
                     *       "password-confirm": "newpassword456"
                     *     }
                     */
                    "application/json": {
                        key: string;
                        password: string;
                        "password-confirm": string;
                    };
                };
            };
            responses: {
                /** @description resets password with valid key */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "Your password has been reset"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns error for invalid reset key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "There was an error resetting your password"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reset-password-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "email": "user_b261355f@example.com"
                     *     }
                     */
                    "application/json": {
                        email: string;
                    };
                };
            };
            responses: {
                /** @description requests a password reset email */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "An email has been sent to you with a link to reset the password for your account"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns error for unknown email */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "field-error": [
                         *         "email",
                         *         "no matching login"
                         *       ],
                         *       "error": "There was an error requesting a password reset"
                         *     }
                         */
                        "application/json": {
                            "field-error": string[];
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verify-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "key": "269_3axdhG00xLlDhq8W33j3GE9Ydr4I_idvIseKQuhGpGA"
                     *     }
                     */
                    "application/json": {
                        key: string;
                    };
                };
            };
            responses: {
                /** @description verifies account with valid key */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "Your account has been verified"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns error for invalid verification key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Unable to verify account"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verify-account-resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend account verification email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "email": "unverified_888af56e@example.com"
                     *     }
                     */
                    "application/json": {
                        email: string;
                    };
                };
            };
            responses: {
                /** @description resends verification email */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "An email has been sent to you with a link to verify your account"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns 401 without authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Unable to resend verify account email"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verify-login-change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify login change */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "key": "273_hyu-z0jEZpR0Ja4c5k1qXR1_YX9qHumthKNDkJ8rky0"
                     *     }
                     */
                    "application/json": {
                        key: string;
                    };
                };
            };
            responses: {
                /** @description verifies login change with valid key */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": "Your login change has been verified"
                         *     }
                         */
                        "application/json": {
                            success: string;
                        };
                    };
                };
                /** @description returns error for invalid key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Unable to verify login change"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
